In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('D:\zzKoding\Data Sains - Machine Learning - AI\Lomba\Satria Data 2020\Data enLer\datatrainbr.xlsx')
df.head()

Unnamed: 0   ID  label                                              judul  \
0           0   71      1  Pemakaian Masker Menyebabkan Penyakit Legionna...   
1           1  461      1  Instruksi Gubernur Jateng tentang penilangan  ...   
2           2  495      1  Foto Jim Rohn: Jokowi adalah presiden terbaik ...   
3           3  550      1  ini bukan politik, tapi kenyataan Pak Jokowi b...   
4           4  681      1       Foto Kadrun kalo lihat foto ini panas dingin   

                                              narasi  \
0  A caller to a radio talk show recently shared ...   
1  Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...   
2  Jokowi adalah presiden terbaik dlm sejarah ban...   
3  Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...   
4        Kadrun kalo lihat foto ini panas dingin . .   

                                               total  
0   pemakaian masker menyebabkan penyakit legionn...  
1   instruksi gubernur jateng penilangan bermaske...  
2   foto jim jokowi presiden terbaik sejarah bang...  
3   politik kenyataan jokowi berhasil memulangkan...  
4   foto lihat foto panas dingin lihat foto panas...

In [3]:
print(df.shape)
df = df.drop(['Unnamed: 0'], axis=1)
df.head()

(4231, 6)


ID  label                                              judul  \
0   71      1  Pemakaian Masker Menyebabkan Penyakit Legionna...   
1  461      1  Instruksi Gubernur Jateng tentang penilangan  ...   
2  495      1  Foto Jim Rohn: Jokowi adalah presiden terbaik ...   
3  550      1  ini bukan politik, tapi kenyataan Pak Jokowi b...   
4  681      1       Foto Kadrun kalo lihat foto ini panas dingin   

                                              narasi  \
0  A caller to a radio talk show recently shared ...   
1  Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...   
2  Jokowi adalah presiden terbaik dlm sejarah ban...   
3  Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...   
4        Kadrun kalo lihat foto ini panas dingin . .   

                                               total  
0   pemakaian masker menyebabkan penyakit legionn...  
1   instruksi gubernur jateng penilangan bermaske...  
2   foto jim jokowi presiden terbaik sejarah bang...  
3   politik kenyataan jokowi berhasil memulangkan...  
4   foto lihat foto panas dingin lihat foto panas...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4231 entries, 0 to 4230
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      4231 non-null   int64 
 1   label   4231 non-null   int64 
 2   judul   4231 non-null   object
 3   narasi  4231 non-null   object
 4   total   4231 non-null   object
dtypes: int64(2), object(3)
memory usage: 165.4+ KB


In [5]:
df['label'].value_counts()

1    3465
0     766
Name: label, dtype: int64

In [6]:
df_t = pd.read_excel('D:\zzKoding\Data Sains - Machine Learning - AI\Lomba\Satria Data 2020\Data enLer\datatestbr - Copy.xlsx')
df_t_id = df_t['ID']
df_t.head()

Unnamed: 0      ID                                              judul  \
0           0  238057  Narasi Tito Karnavian Berideologi Komunis Kare...   
1           1  238158  Anies: Seberat beratnya Pekerjaan Akan terasa ...   
2           2  238865  Hindu di india Melemparkan Patung Buatan Merek...   
3           3  248298  RSCM Praktekkan Penyedotan Plug  Vena/Saluran ...   
4           4  255176             Permohonan Kelonggaran Angsuran ke OJK   

                                              narasi  label  \
0  TITO KARNIVAN ITU BERIDIOLOGI KOMUNIS DIA BISA...      1   
1  Seberat beratnya Pekerjaan Akan terasa ringan ...      1   
2  Hindu di india melemparkan patung buatan merek...      1   
3  Mulai Hari ini di RSCM mulai diPraktekkan Peny...      1   
4  Untuk sekedar info, Bagi anda yg punya ansuran...      1   

                                               total  
0   narasi tito berideologi komunis disekolahkan ...  
1   anies seberat beratnya pekerjaan ringan kerja...  
2   hindu india melemparkan patung buatan laut me...  
3   rscm praktekkan penyedotan plug darah rscm di...  
4   permohonan kelonggaran angsuran ojk info kelo...

In [7]:
df_t = df_t.drop(['Unnamed: 0'], axis=1)
df_t.head()

ID                                              judul  \
0  238057  Narasi Tito Karnavian Berideologi Komunis Kare...   
1  238158  Anies: Seberat beratnya Pekerjaan Akan terasa ...   
2  238865  Hindu di india Melemparkan Patung Buatan Merek...   
3  248298  RSCM Praktekkan Penyedotan Plug  Vena/Saluran ...   
4  255176             Permohonan Kelonggaran Angsuran ke OJK   

                                              narasi  label  \
0  TITO KARNIVAN ITU BERIDIOLOGI KOMUNIS DIA BISA...      1   
1  Seberat beratnya Pekerjaan Akan terasa ringan ...      1   
2  Hindu di india melemparkan patung buatan merek...      1   
3  Mulai Hari ini di RSCM mulai diPraktekkan Peny...      1   
4  Untuk sekedar info, Bagi anda yg punya ansuran...      1   

                                               total  
0   narasi tito berideologi komunis disekolahkan ...  
1   anies seberat beratnya pekerjaan ringan kerja...  
2   hindu india melemparkan patung buatan laut me...  
3   rscm praktekkan penyedotan plug darah rscm di...  
4   permohonan kelonggaran angsuran ojk info kelo...

In [8]:
print(df_t.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470 entries, 0 to 469
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      470 non-null    int64 
 1   judul   470 non-null    object
 2   narasi  470 non-null    object
 3   label   470 non-null    int64 
 4   total   470 non-null    object
dtypes: int64(2), object(3)
memory usage: 18.5+ KB
None


In [9]:
#inisiasi x dan y
x_train = df['total']
y_train = df['label']

In [10]:
x_test = df_t['total']
y_test = df_t['label']

In [11]:
# Initialize a TfidfVectorizer
tfidf_vectorizer=TfidfVectorizer(max_df=1.0)

#Fit and transform train set, transform test set
tfidf_train=tfidf_vectorizer.fit_transform(x_train)
tfidf_test=tfidf_vectorizer.transform(x_test)

In [12]:
print(tfidf_train.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
tfidf_train_array = tfidf_train.toarray()
tfidf_test_array = tfidf_test.toarray()
tfidf_train_df = pd.DataFrame(tfidf_train_array)
tfidf_test_df = pd.DataFrame(tfidf_test_array)
display(tfidf_train_df.head())
display(tfidf_test_df.head())

0      1      2      3      4      5      6      7      8      9      ...  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   16769  16770  16771  16772  16773  16774  16775  16776  16777  16778  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 16779 columns]

0      1      2      3      4      5      6      7      8      9      ...  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   16769  16770  16771  16772  16773  16774  16775  16776  16777  16778  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 16779 columns]

In [14]:
subset4_x, subset4_y = tfidf_train_df, y_train

In [15]:
from sklearn.ensemble import RandomForestClassifier

# Create the model with 100 trees
model = RandomForestClassifier(n_estimators=100, 
                               bootstrap = True,
                               max_features = 'sqrt')
# Fit on training data
model.fit(subset4_x, subset4_y)
y_pred4 = model.predict(tfidf_test_df)
score4 = metrics.f1_score(y_test, y_pred4)
print(f'F1 Score: {round(score4*100,2)}%')

F1 Score: 94.92%


In [16]:
from sklearn.model_selection import RandomizedSearchCV

In [17]:
n_estimators = [100, 300, 500, 800, 1200]
max_depth = [5, 8, 15, 25, 30]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10] 

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

In [ ]:
rf = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
rf_random.fit(subset4_x, subset4_y)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed: 42.7min


In [ ]:
rf_random.best_params_